version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo "Instalando sonar-scanner"
      - curl -sSLo /tmp/sonar.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
      - unzip -q /tmp/sonar.zip -d /tmp
      - export PATH="/tmp/sonar-scanner-5.0.1.3006-linux/bin:$PATH"
      - echo "Obteniendo SONAR_TOKEN desde Parameter Store"
      - export SONAR_TOKEN=$(aws ssm get-parameter --name SONAR_TOKEN --with-decryption --query "Parameter.Value" --output text)
  build:
    commands:
      - echo "Ejecutando análisis SAST con SonarCloud"
      - sonar-scanner -Dsonar.login=$SONAR_TOKEN
      # Esperar un poco a que se procese en SonarCloud
      - echo "Esperando resultados de SonarCloud..."
      - sleep 30
      # Descargar resultados de issues directamente de la API de SonarCloud
      - echo "Verificando vulnerabilidades Medium o superiores"
      - |
        curl -s -u $SONAR_TOKEN: "https://sonarcloud.io/api/issues/search?componentKeys=nchavezm20_devsecops-laboratorio&severities=BLOCKER,CRITICAL,MAJOR" > result.json
        COUNT=$(jq '.total' result.json)
        echo "Total vulnerabilidades críticas, altas o medias: $COUNT"
        if [ "$COUNT" -gt 0 ]; then
          echo "❌ Se encontraron vulnerabilidades Medium o superiores. Fallando pipeline."
          exit 1
        else
          echo "✅ Sin vulnerabilidades Medium o superiores. Continuando pipeline."
        fi

artifacts:
  files:
    - .scannerwork/report-task.txt
  discard-paths: yes
